services:
   
  mysql:
    image: mysql:latest
    container_name: mysql_db
    volumes:
      - mysql-data:/var/lib/mysql 
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=omrsheet
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - omr-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin 
    environment:
    - PMA_HOST=mysql
    - PMA_PORT=3306
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - omr-network
    
  nodeapp:
    image: nodeapp:latest
    container_name: nodeapp
    ports:
      - 4000: 4000
    depends_on:
      - mysql
    restart: always
    networks:
      - omr-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  reactapp:
    image: reactapp:latest
    container_name: reactapp
    ports:
      - 3000: 3000
    depends_on:
      - mysql
    restart: always
    networks:
      - omr-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
networks:
  omr-network:
volumes:
  mysql-data:
    